import{a as E,S as L,i as b,b as p}from"./assets/vendor-ea274875.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const v="42508369-6cc99fb978405cb8598a23b23",w="https://pixabay.com/api/",$="photo",R="horizontal",S=!0,m=15;async function g(r,t=1){try{const n=encodeURIComponent(r),i=`${w}?key=${v}&q=${n}&image_type=${$}&orientation=${R}&safesearch=${S}&per_page=${m}&page=${t}`,e=await E.get(i);if(e.status!==200)throw new Error("Image error");return e.data}catch(n){throw console.error("Error fetching images:",n),new Error("Error while fetching images from pixabay",n)}}function I(r){r.innerHTML=""}function y(r,t){const n=r.map(e=>`

        <li class="gallery-item" >

         <a href="${e.webformatURL}"><img class="card-image" src="${e.webformatURL}" alt="${e.tags}" />
         <div class="card-info">
           <p>Likes: <span>${e.likes}</span></p>
           <p>Views: <span>${e.views}</span></p>
           <p>Comments: <span>${e.comments}</span></p>
           <p>Downloads:<span>${e.downloads}</span></p>
         </div></a>
       </li> `).join("");t.innerHTML+=n,new L(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function a(r){b.error({title:"Error",message:r,position:"topRight"})}const P=document.querySelector(".form"),f=document.querySelector(".search-input"),d=document.querySelector(".gallery"),h=document.getElementById("loader"),s=document.querySelector("#loadMoreBtn");let l="",c=1;P.addEventListener("submit",async function(r){if(r.preventDefault(),l=f.value.trim(),l===""){a("Please fill input");return}f.value="",h.classList.remove("is-hidden"),I(d),c=1;try{const t=await g(l,c);if(t.hits.length===0){a("Sorry, there are no images matching your search query. Please try again!");return}y(t.hits,d),t.totalHits>m&&s.classList.remove("is-hidden")}catch(t){console.error("Error during search:",t),a("Error during search")}finally{h.classList.add("is-hidden")}});s.addEventListener("click",async function(){if(!navigator.onLine){d.innerHTML="",s.classList.add("is-hidden"),p.error({title:"Error",message:"No internet connection",position:"topRight"});return}const r=document.getElementById("load-more-loader");r.classList.remove("is-hidden"),s.classList.add("is-hidden");try{const t=await g(l,c+1);c++,M(t),c*m>=t.totalHits&&(s.classList.add("is-hidden"),q()),s.scrollIntoView({behavior:"smooth",block:"end"})}catch(t){console.error("Error during loading more images:",t),a("Error loading more images")}finally{r.classList.add("is-hidden"),s.disabled=!1}});function q(){p.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function M(r){var t;if(r.hits.length===0){a("Sorry, there are no images matching your search query. Please try again!");return}s.classList.contains("is-hidden")&&s.classList.remove("is-hidden"),y(r.hits,d),(t=document.querySelector(".gallery-item"))!=null&&t.getBoundingClientRect().height}
//# sourceMappingURL=commonHelpers.js.map
